spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
server.port: 8081

sid:
  client:
    relyingPartyUuid: ${SID_RELYING_PARTY_UUID}
    relyingPartyName: ${SID_RELYING_PARTY_NAME}
    applicationProviderHost: https://sid.demo.sk.ee/smart-id-rp/v3/
    polling-timeout-in-seconds: 5
    dynamic-link-url: https://sid.demo.sk.ee/dynamic-link/
    open-socket-timeout-in-seconds: 1
  auth:
    displayText: Log in with Smart-ID demo?
  truststore:
    trusted-server-ssl-certs:
      filename: /sid.trusted_server_certs.p12
      password: changeit
    trusted-root-certs:
      filename: /sid.trusted_root_certs.p12
      password: changeit

app:
  signed-files-directory: target/signed-files